# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 23:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('idVendedor', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('categorias', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Cerdo'), (1, 'Chino'), (2, 'Completos'), (3, 'Egipcio'), (4, 'Empanadas'), (5, 'Ensalada'), (6, 'Japones'), (7, 'Pan'), (8, 'Papas fritas'), (9, 'Pasta'), (10, 'Pescado'), (11, 'Pollo'), (12, 'Postres'), (13, 'Sushi'), (14, 'Vacuno'), (15, 'Vegano'), (16, 'Vegetariano')], max_length=40)),
                ('descripcion', models.CharField(max_length=500)),
                ('stock', models.PositiveSmallIntegerField(default=0)),
                ('precio', models.PositiveSmallIntegerField(default=0)),
                ('imagen', models.ImageField(upload_to='productos')),
            ],
            options={
                'db_table': 'Comida',
            },
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idAlumno', models.IntegerField()),
                ('idVendedor', models.IntegerField()),
            ],
            options={
                'db_table': 'Favoritos',
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='avatars')),
            ],
            options={
                'db_table': 'imagen',
            },
        ),
        migrations.CreateModel(
            name='Transacciones',
            fields=[
                ('idTransaccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombreComida', models.CharField(blank=True, max_length=200, null=True)),
                ('idVendedor', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('fecha', models.CharField(default='2017-06-16', max_length=200)),
            ],
            options={
                'db_table': 'transacciones',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('tipo', models.IntegerField(choices=[(0, 'admin'), (1, 'alumno'), (2, 'fijo'), (3, 'ambulante')])),
                ('avatar', models.ImageField(upload_to='avatars')),
                ('contraseña', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=False)),
                ('formasDePago', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Efectivo'), (1, 'Tarjeta de Crédito'), (2, 'Tarjeta de Débito'), (3, 'Tarjeta Junaeb')], max_length=7, null=True)),
                ('horarioIni', models.CharField(blank=True, max_length=200, null=True)),
                ('horarioFin', models.CharField(blank=True, max_length=200, null=True)),
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abstract_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
